In [1]:
# NumPy- is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. 
# Array- is a data structure that stores values of same data type. In python this is the main difference between arrays and lists. 
#array contains values corresponding to same data type.


In [2]:
import numpy as np

In [6]:
my_lst=[1,2,3,4,5,6]
arr=np.array(my_lst)

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr

array([1, 2, 3, 4, 5, 6])

In [9]:
arr.shape

(6,)

In [10]:
lst1=[1,2,3,4]
lst2=[5,6,7,8]
lst3=[9,10,11,12]
arr=np.array([lst1,lst2,lst3])

In [11]:
arr


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
arr.shape

(3, 4)

In [13]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
#indexing
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
arr.shape

(3, 4)

In [19]:
arr[1:,:-1]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [20]:
arr[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [28]:
arr[1:2,1:3]

array([[6, 7]])

In [29]:
arr1=np.arange(0,10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [36]:
#copying
arr=[1,2,3,4,5,6,7,8,9]
arr=np.array(arr)

In [37]:
arr1=arr

In [38]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr1[3:]=500

In [40]:
arr1

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [41]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [42]:
arr1=arr.copy()

In [43]:
print(arr)

[  1   2   3 500 500 500 500 500 500]


In [44]:
arr1[3:]=1000

In [45]:
arr1

array([   1,    2,    3, 1000, 1000, 1000, 1000, 1000, 1000])

In [50]:
### some conditions are very useful for EDA
val=1
print(arr*2)
print(arr[arr<2])

[   2    4    6 1000 1000 1000 1000 1000 1000]
[1]


In [47]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [54]:
np.ones(5) #default dtype is float

array([1., 1., 1., 1., 1.])

In [52]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [55]:
np.random.rand(3,4) #uniform dist.

array([[0.58445664, 0.42555915, 0.87328609, 0.35504805],
       [0.51871376, 0.9441745 , 0.47598508, 0.09075781],
       [0.2803372 , 0.99152394, 0.47229298, 0.41424061]])

In [58]:
arr_ex=np.random.randn(4,5) #random value with stand normal distribution
arr_ex

array([[-0.82253914,  1.50660492,  0.12131528, -1.52000311,  1.31223842],
       [-0.58272081,  0.43704429,  0.66478151,  0.83921737, -1.11831817],
       [-0.27300148,  0.30149672,  0.29074592, -0.77284296, -0.47875981],
       [-0.17647591,  0.00430849, -0.72929467,  0.63074967, -0.67738326]])

In [59]:
np.random.randint(0,100,10)

array([65, 82, 15, 30, 11, 44, 95, 12, 39, 75])

In [60]:
np.random.random_sample((1,5))

array([[0.06133118, 0.87248489, 0.30240385, 0.3255268 , 0.50183076]])